"""
Dashboard Data
"""
my_activity = """
{
    "id": 1,
    "title": "My Activity",
    "name": "my_activity",
    "type": "feed",
    "url": "/perfweb/pdashboard/dashboards/?board=my_activity",
    "search": "(select a.id, concat('/perfweb/pweb/perfscheduler/?page=policy&lu_enable_query=1&id=', a.id) as id_url, concat('/perfweb/pweb/user/?username=', a.created_by) as user_url, 'Perf Scheduler' as title, a.created_at, a.created_by, concat('/', c.img) as img from pperfscheduler_perfpolicy as a, puser_user as b, pfile_userimage as c where a.created_by = '$current_user$' and a.created_by = b.username and b.id = c.user_id order by a.created_at desc limit {limit} offset {offset}) UNION (select a.id, concat('/perfweb/pweb/envresource/?lu_enable_query=1&id=', a.id) as id_url, concat('/perfweb/pweb/user/?username=', a.created_by) as user_url, 'Splunk Instance' as title, a.created_at, a.created_by, concat('/', c.img) as img from presource_envinstance as a, puser_user as b, pfile_userimage as c where a.created_by = '$current_user$' and a.created_by = b.username and b.id = c.user_id order by a.created_at desc limit {limit} offset {offset}) UNION (select a.id, concat('/perfweb/pweb/diag/?lu_enable_query=1&id=', a.id) as id_url, concat('/perfweb/pweb/user/?username=', a.created_by) as user_url, 'Splunk Diag' as title, a.created_at, a.created_by, concat('/', c.img) as img from pfile_customerfile as a, puser_user as b, pfile_userimage as c where a.created_by = '$current_user$' and a.created_by = b.username and b.id = c.user_id order by a.created_at desc limit {limit} offset {offset}) UNION (select a.id, concat('/perfweb/pweb/clouddatagen/?lu_enable_query=1&id=', a.id) as id_url, concat('/perfweb/pweb/user/?username=', a.created_by) as user_url, 'AWS S3 Data' as title, a.created_at, a.created_by, concat('/', c.img) as img from pdatagen_clouddatagen as a, puser_user as b, pfile_userimage as c where a.created_by = '$current_user$' and a.created_by = b.username and b.id = c.user_id order by a.created_at desc limit {limit} offset {offset}) UNION (select a.id, concat('/perfweb/pweb/benchmark_io/?lu_enable_query=1&id=', a.id) as id_url, concat('/perfweb/pweb/user/?username=', a.created_by) as user_url, 'IO Benchmark' as title, a.created_at, a.created_by, concat('/', c.img) as img from pbenchmark_io as a, puser_user as b, pfile_userimage as c where a.created_by = '$current_user$' and a.created_by = b.username and b.id = c.user_id order by a.created_at desc limit {limit} offset {offset})",
    "search_param": "{\"limit\": \"5\", \"offset\": \"0\"}",
    "fixed_data": "0",
    "color": "green",
    "size": "eight wide",
    "state": "show",
    "created_at": "2017-03-27T17:50:54.554232",
    "updated_at": "2018-01-04T17:19:02.230260",
    "created_by": "default",
    "group": "public",
    "comment": "Default My activity",
    "index": 100,
    "template": "my_activity_board.html",
    "js_template": "my_activity_board.js",
    "status": "enable",
    "refresh": 0,
    "process": "1",
    "shared_by": null,
    "pre_size": "eight wide",
    "height": "0",
    "pre_height": "450",
    "enable_header_menu": "True",
    "enable_resize": "True",
    "enable_save": "True"
}
"""

online_service="""
{
    "id": 2,
    "title": "Online Service",
    "name": "online_service",
    "type": "card",
    "url": "/perfweb/pdashboard/dashboards/?board=online_service",
    "search": "[{\"url\": \"/perfweb/pweb/perfscheduler?page=job\", \"name\": \"Perf Test Scheduler\", \"color\": \"teal\", \"icon\": \"spinner\", \"description\": \"A smart scheduler can run performance test with specific policy in more efficient way\", \"done\": \"lu_sql:select count(*) as done from pperfscheduler_perfscheduler where status=\\\"done\\\"\", \"run\": \"lu_sql:select count(*) as run from pperfscheduler_perfscheduler where status=\\\"running\\\"\", \"pending\": \"lu_sql:select count(*) as pending from pperfscheduler_perfscheduler where status in (\\\"pending\\\", \\\"created\\\")\", \"timeout\": \"lu_sql:select count(*) as timeout from pperfscheduler_perfscheduler where status=\\\"timeout\\\"\" }, {\"url\": \"/perfweb/pweb/benchmark_io\", \"name\": \"Disk IO Benchmark by FIO\", \"color\": \"violet\", \"icon\": \"disk outline\", \"description\": \"Leverage Perfkit Benchmarker to define a canonical set of benchmarks to measure and compare cloud offerings\", \"total\": \"lu_sql:select count(*) as total from pbenchmark_io\", \"success\": \"lu_sql:select count(*) as success from pbenchmark_io where status=\\\"done\\\"\", \"run\": \"lu_sql:select count(*) as stop from pbenchmark_io where status=\\\"running\\\"\" }, {\"url\": \"/perfweb/pweb/perfharness\", \"name\": \"Perfharness Test Builder\", \"color\": \"red\", \"icon\": \"rocket\", \"description\": \"Leverage orca to create test environment, conductor as the test engine to do the performance testing\", \"total\": \"lu_sql:select count(*) as total from pperfharness_perfharnesstest\", \"success\": \"lu_sql:select count(*) as success from pperfharness_perfharnesstest where status=\\\"done\\\"\" },{\"url\": \"/perfweb/pweb/envresource\", \"name\": \"Splunk Instance\", \"color\": \"red\", \"icon\": \"cubes\", \"description\": \"Create Splunk Instance In AWS EC2, provision specified splunk/app/ta version\", \"total\": \"lu_sql:select count(*) as total from presource_envinstance\", \"run\": \"lu_sql:select count(*) as run from presource_envinstance where status=\\\"running\\\"\", \"stop\": \"lu_sql:select count(*) as stop from presource_envinstance where status=\\\"stopped\\\"\" },{\"url\": \"/perfweb/pweb/diag\",\"name\": \"Splunk Diag\",\"color\":\"yellow\", \"icon\": \"cloud upload\", \"description\": \"Upload and analyze custom profile\", \"total\": \"lu_sql:select count(*) as total from pfile_customerfile\", \"success\": \"lu_sql:select count(*) as success from pfile_customerfile where report_status=\\\"SUCCESS\\\"\"}]",
    "search_param": "{\"card_number\":\"four\"}",
    "fixed_data": "1",
    "color": "green",
    "size": "ten wide",
    "state": "show",
    "created_at": "2017-03-27T17:52:19.911681",
    "updated_at": "2017-12-14T13:02:27.262238",
    "created_by": "default",
    "group": "public",
    "comment": "Online service",
    "index": 0,
    "template": "online_service_board.html",
    "js_template": null,
    "status": "enable",
    "refresh": 0,
    "process": "1",
    "shared_by": null,
    "pre_size": "eight wide",
    "height": "490",
    "pre_height": "450",
    "enable_header_menu": "True",
    "enable_resize": "True"
}
"""

jhu_web_entry="""
{
    "id": 14,
    "title": "Bookmark",
    "name": "jhu_web_entry",
    "type": "card",
    "url": "/perfweb/pdashboard/dashboards/",
    "search": "[{\"url\": \"https://confluence.splunk.com/\", \"name\": \"Confluence\", \"color\": \"red\", \"icon\": \"flag\", \"description\": \"Document center\"}, {\"url\": \"https://jira.splunk.com/secure/RapidBoard.jspa?rapidView=877&quickFilter=12637\",\"name\": \"Jira\",\"color\":\"orange\", \"icon\": \"flag\", \"description\": \"Issue and bug\"},{\"url\": \"https://git.splunk.com/projects/PERF/repos/perf-ta-datacollection/browse\", \"name\": \"Bitbucket\", \"color\": \"yellow\", \"icon\": \"flag\", \"description\": \"Code\"},{\"url\": \"https://ap-southeast-1.console.aws.amazon.com/console/home?region=ap-southeast-1#\", \"name\": \"AWS Console\", \"color\": \"olive\", \"icon\": \"flag\", \"description\": \"AWS resource\"},{\"url\": \"https://portal.azure.com/#dashboard/private/42fd72e6-4b5c-4e3b-9d06-875c41fc5018\", \"name\": \"Azure Console\", \"color\": \"purple\", \"icon\": \"flag\", \"description\": \"Azure console\"},{\"url\": \"https://pto.splunk.io/web\", \"name\": \"PTO System\", \"color\": \"green\", \"icon\": \"flag\", \"description\": \"Holiday\"},{\"url\": \"https://confluence.splunk.com/display/SHAN/Check+Point+OPSEC+LEA+4.0.0+VS+fw1-loggrabber+Performance+Test+Report\", \"name\": \"OPSEC Performance\", \"color\": \"teal\", \"icon\": \"flag\", \"description\": \"Opsec perf report\"},{\"url\": \"https://confluence.splunk.com/display/SHAN/MS+Cloud+2.0.0+Performance+Report\", \"name\": \"Mscloud Performance\", \"color\": \"blue\", \"icon\": \"flag\", \"description\": \"Mscloud perf report\"}, {\"url\": \"https://confluence.splunk.com/display/SHAN/AWS+Performance+Test+Coverage\", \"name\": \"AWS Performance\", \"color\": \"violet\", \"icon\": \"flag\", \"description\": \"AWS perf\"}, {\"url\": \"https://confluence.splunk.com/display/PROD/Avanti+Quick+Start+Guide\", \"name\": \"Anvanti\", \"color\": \"purple\", \"icon\": \"flag\", \"description\": \"Anvanti guide\"}, {\"url\": \"https://confluence.splunk.com/display/PROD/Getting+Started+with+Orca\", \"name\": \"Orca\", \"color\": \"pink\", \"icon\": \"flag\", \"description\": \"Orca guide\"}, {\"url\": \"http://ucp-sh01:8000/en-US/app/search/search?q=search (index=appperf) source=http:perf_ta_datacollection test_label=kimono-test-jhu-20170406-2 | rename test_name as test_category,data_collection_metrics.duration as index_duration data_collection_metrics.kpi_eps as eps ,data_collection_metrics.kpi_eps2 as eps2 , data_collection_metrics.kpi_kbps as kbps,data_collection_metrics.kpi_kbps2 as kbps2, resource_metrics.sys_cpu_avg as sys_cpu_avg , resource_metrics.sys_cpu_max as sys_cpu_max , resource_metrics.sys_memory_avg as sys_memory_avg , resource_metrics.sys_memory_max as sys_memory_max | stats avg(duration) as duration avg(index_duration) as index_duration avg(eps) as eps avg(kbps) as kbps avg(eps2) as eps2 avg(kbps2) as kbps2 avg(sys_cpu_avg) as sys_cpu_avg avg(sys_cpu_max) as sys_cpu_max avg(sys_memory_avg) as sys_memory_avg avg(sys_memory_max) as sys_memory_max by test_category, product_name,product_version,splunk_version,test_scenario  |table test_category, splunk_version,product_version, test_scenario, duration,index_duration, eps, eps2, kbps, kbps2, sys_cpu_avg, sys_cpu_max, sys_memory_avg, sys_memory_max | sort test_scenario, splunk_version | chart avg(kbps2) by test_scenario, splunk_version&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=0&latest=&display.page.search.tab=visualizations&display.general.type=visualizations&display.visualizations.charting.chart.showDataLabels=all&sid=1491535143.2670\", \"name\": \"AWS Report\", \"color\": \"red\", \"icon\": \"flag\", \"description\": \"report in ucp-sh\"}]",
    "search_param": "{\"card_number\": \"eight\",\"target\":\"_blank\"}",
    "fixed_data": "1",
    "color": "yellow",
    "size": "sixteen wide",
    "state": "show",
    "created_at": "2017-03-30T16:57:04.997284",
    "updated_at": "2017-12-21T21:15:01.434644",
    "created_by": "jhu",
    "group": "private",
    "comment": "Online service",
    "index": 3,
    "template": "online_service_board.html",
    "js_template": null,
    "status": "enable",
    "refresh": 0,
    "process": "1",
    "shared_by": null,
    "pre_size": "eight wide",
    "height": "0",
    "pre_height": "30",
    "enable_header_menu": "True",
    "enable_resize": "True"
}
"""

splunk_instance_table="""
{
    "id": 30,
    "title": "My Splunk Instance(table)",
    "name": "splunk_instance_table",
    "type": "table",
    "url": "/perfweb/pdashboard/dashboards/",
    "search": null,
    "search_param": "{\"title\":[[\"ID\", \"id\"], [\"Name\", \"name\"], [\"Type\", \"type\"], [\"Owner\", \"owner\"], [\"OS\", \"os\"], [\"Project\", \"project\"], [\"Created Time\", \"created_at\"], [\"Status\", \"status\"]], \"query\": \"select id, name, type, owner, os, project, created_at, status from presource_envinstance\"}",
    "fixed_data": "0",
    "color": "olive",
    "size": "sixteen wide",
    "state": "none",
    "created_at": "2017-04-01T14:04:10.448373",
    "updated_at": "2018-01-25T17:22:15.805048",
    "created_by": "jhu",
    "group": "private",
    "comment": "Table example",
    "index": 10,
    "template": "basic_table_board.html",
    "js_template": "basic_table_board.js",
    "status": "enable",
    "refresh": 300,
    "process": "1",
    "shared_by": null,
    "pre_size": "sixteen wide",
    "height": "30",
    "pre_height": "1000",
    "footer_height": 0,
    "enable_header_menu": "True",
    "enable_resize": "True",
    "enable_save": "True"
}
"""

ucp_container_usage = """
{
    "id": 100,
    "title": "UCP Perf Container Usage",
    "name": "ucp_container_usage",
    "type": "chart",
    "url": "/perfweb/pdashboard/dashboards/?board=ucp_container_usage&group=scheduler_job",
    "search": "select 'free' as l_data, free as y_data, updated_at from pperfscheduler_ucpcontainer union (select 'busy' as l_data, busy as y_data, updated_at from pperfscheduler_ucpcontainer)",
    "search_param": "{\"limit\":\"1\", \"offset\":\"0\", \"height\":\"200\", \"title_text\":\"Perf Container\",\"y_name\": \"Number\"}",
    "fixed_data": "0",
    "color": "green",
    "size": "five wide",
    "state": "show",
    "created_at": "2017-12-11T17:21:21.017848",
    "updated_at": "2018-01-04T17:42:59.371541",
    "created_by": "default",
    "group": "scheduler_job",
    "comment": "Public ucp container usage in scheduler page",
    "index": 3,
    "template": "ucp_container_pie.html",
    "js_template": "ucp_container_pie.js",
    "status": "enable",
    "refresh": 120,
    "process": "1",
    "shared_by": null,
    "pre_size": "eight wide",
    "height": "250",
    "pre_height": "450",
    "enable_header_menu": "True",
    "enable_resize": "True",
    "enable_save": "False"
}
"""

schedule_job_container_usage = """
{
    "id": 119,
    "title": "Schedule Job Container Usage",
    "name": "schedule_job_container_usage",
    "type": "chart",
    "url": "/perfweb/pdashboard/dashboards/?board=schedule_job_container_usage&group=scheduler_job",
    "search": "(select used_container as y, 'used container' as legend, concat_ws('-', policy_name, id) as x from pperfscheduler_perfscheduler where status = 'running') union (select max_container as y, 'max container threshold' as legend, concat_ws('-', policy_name, id) as x from pperfscheduler_perfscheduler where status = 'running') limit ${limit} offset 0",
    "search_param": "{\"limit\":\"100000\", \"offset\":\"0\", \"height\":\"200\",\"yAxis\": {\"title\": {\"text\": \"Container Number\"}, \"minTickInterval\": 1}, \"title\": {\"text\": \"Job Container Usage\"}, \"series\":{\"All\": {\"visible\": \"true\"}}}",
    "fixed_data": "0",
    "color": "green",
    "size": "five wide",
    "state": "show",
    "created_at": "2017-12-21T16:27:35.629329",
    "updated_at": "2018-01-04T17:43:42.099386",
    "created_by": "default",
    "group": "scheduler_job",
    "comment": "Application scheduler owns the board",
    "index": 4,
    "template": "echart_board.html",
    "js_template": "basic_column_category_highchart_board.js",
    "status": "enable",
    "refresh": 60,
    "process": "1",
    "shared_by": null,
    "pre_size": "ten wide",
    "height": "250",
    "pre_height": "450",
    "enable_header_menu": "True",
    "enable_resize": "True",
    "enable_save": "False"
}
"""

schedule_times_by_policy="""
{
    "id": 118,
    "title": "Schedule Times By Policy",
    "name": "schedule_times_by_policy",
    "type": "chart",
    "url": "/perfweb/pdashboard/dashboards/?board=schedule_times_by_policy&group=scheduler_job",
    "search": "select policy_name as l_data, count(*) as y_data from pperfscheduler_perfscheduler group by policy_name",
    "search_param": "{\"limit\":\"1\", \"offset\":\"0\", \"height\":\"200\", \"title_text\":\"Schedule Times\",\"y_name\": \"Number\"}",
    "fixed_data": "0",
    "color": "green",
    "size": "six wide",
    "state": "show",
    "created_at": "2017-12-21T14:26:54.393920",
    "updated_at": "2017-12-21T17:41:47.420840",
    "created_by": "default",
    "group": "scheduler_job",
    "comment": "Schedule times by policy",
    "index": 6,
    "template": "echart_board.html",
    "js_template": "basic_pie_echart_board.js",
    "status": "enable",
    "refresh": 300,
    "process": "1",
    "shared_by": null,
    "pre_size": "eight wide",
    "height": "250",
    "pre_height": "450",
    "enable_header_menu": "False",
    "enable_resize": "False"
}
"""

schedule_status_by_time="""
{
    "id": 117,
    "title": "Schedule Job Status by Time",
    "name": "schedule_status_by_time",
    "type": "chart",
    "url": "/perfweb/pdashboard/dashboards/?board=schedule_status_by_time&group=scheduler_job",
    "search": "select count(j.status) as y, concat_ws('-', s.policy_name, j.status) as legend, DATE_FORMAT(s.created_at, '%Y-%m-%d %H:%I:%S') as x from pperfscheduler_perfscheduler as s, pperfscheduler_perftestscheduler as j, pperfscheduler_perfpolicy as p where s.id = j.scheduler_id and s.policy_name = p.name and p.trigger=\"cron\" group by DATE_FORMAT(s.created_at, '%Y-%m-%d %H:%I:%S'), j.status, s.policy_name",
    "search_param": "{\"limit\":\"100000\", \"offset\":\"0\", \"height\":\"200\", \"yAxis\": {\"title\": {\"text\": \"Test Case Number\"}, \"minTickInterval\": 1}, \"title\": {\"text\": \"Job Status by Time\"}, \"series\":{\"Daily Run\": {\"visible\": \"true\"}}}",
    "fixed_data": "0",
    "color": "green",
    "size": "eight wide",
    "state": "show",
    "created_at": "2017-12-20T23:11:12.964412",
    "updated_at": "2018-01-04T17:57:39.703992",
    "created_by": "default",
    "group": "scheduler_job",
    "comment": "Application scheduler owns the board",
    "index": 10,
    "template": "echart_board.html",
    "js_template": "basic_highchart_board.js",
    "status": "enable",
    "refresh": 60,
    "process": "1",
    "shared_by": null,
    "pre_size": "ten wide",
    "height": "450",
    "pre_height": "450",
    "enable_header_menu": "True",
    "enable_resize": "True",
    "enable_save": "False"
}
"""

schedule_duration_by_time = """
{
    "id": 120,
    "title": "Schedule Job Duration by Time",
    "name": "schedule_duration_by_time",
    "type": "chart",
    "url": "/perfweb/pdashboard/dashboards/?board=schedule_duration_by_time&group=scheduler_job",
    "search": "select TIMESTAMPDIFF(SECOND, created_at, ended_at) as y, DATE_FORMAT(created_at, '%Y-%m-%d %H:%I:%S') as x, policy_name as legend from pperfscheduler_perfscheduler where status = 'done' and policy_name in (select distinct(name) from pperfscheduler_perfpolicy where pperfscheduler_perfpolicy.trigger=\"cron\") limit ${limit} offset 0",
    "search_param": "{\"limit\":\"100000\", \"offset\":\"0\", \"height\":\"200\", \"yAxis\": {\"title\": {\"text\": \"Job Duration(sec)\"}, \"minTickInterval\": 1}, \"title\": {\"text\": \"Job Duration by Time\"}, \"series\":{\"Daily Run\": {\"visible\": \"true\"}}}",
    "fixed_data": "0",
    "color": "green",
    "size": "eight wide",
    "state": "show",
    "created_at": "2017-12-21T17:23:35.459751",
    "updated_at": "2018-01-04T17:59:39.321720",
    "created_by": "default",
    "group": "scheduler_job",
    "comment": "Application scheduler owns the board",
    "index": 15,
    "template": "echart_board.html",
    "js_template": "basic_highchart_board.js",
    "status": "enable",
    "refresh": 60,
    "process": "1",
    "shared_by": null,
    "pre_size": "ten wide",
    "height": "450",
    "pre_height": "450",
    "enable_header_menu": "True",
    "enable_resize": "True",
    "enable_save": "False"
}
"""

testcase_by_total = """
{
    "id": 114,
    "title": "Total Test Case",
    "name": "testcase_by_total",
    "type": "chart",
    "url": "/perfweb/pdashboard/dashboards/?board=testcase_by_total&group=scheduler_testcase",
    "search": "select count(*) as value from pperfscheduler_perftest where pperfscheduler_perftest.group=\"${group}\" and branch=\"${branch}\"",
    "search_param": "{\"limit\":\"1\", \"offset\":\"0\", \"label\": \"total\", \"color\": \"violet\", \"group\": \"perf\", \"branch\": \"develop\"}",
    "fixed_data": "0",
    "color": "green",
    "size": "three wide",
    "state": "show",
    "created_at": "2017-12-15T23:09:27.736432",
    "updated_at": "2017-12-16T16:01:09.546965",
    "created_by": "default",
    "group": "scheduler_testcase",
    "comment": "Application scheduler owns the board",
    "index": 0,
    "template": "single_value.html",
    "js_template": "single_value.js",
    "status": "enable",
    "refresh": 0,
    "process": "1",
    "shared_by": null,
    "pre_size": "ten wide",
    "height": "300",
    "pre_height": "450",
    "enable_header_menu": "False",
    "enable_resize": "False"
}
"""

testcase_by_priority = """
{
    "id": 115,
    "title": "Test Case by Priority",
    "name": "testcase_by_priority",
    "type": "chart",
    "url": "/perfweb/pdashboard/dashboards/?board=testcase_by_priority&group=scheduler_testcase",
    "search": "select count(*) as y_data, priority as l_data from pperfscheduler_perftest where pperfscheduler_perftest.group=\"${group}\" and branch=\"${branch}\" group by priority",
    "search_param": "{\"limit\":\"1\", \"offset\":\"0\", \"height\":\"200\", \"title_text\":\"By Priority\",\"y_name\": \"Number\", \"group\": \"perf\", \"branch\": \"develop\"}",
    "fixed_data": "0",
    "color": "green",
    "size": "five wide",
    "state": "show",
    "created_at": "2017-12-15T23:10:08.502475",
    "updated_at": "2017-12-16T15:59:23.624043",
    "created_by": "default",
    "group": "scheduler_testcase",
    "comment": "Application scheduler owns the board",
    "index": 5,
    "template": "echart_board.html",
    "js_template": "basic_pie_echart_board.js",
    "status": "enable",
    "refresh": 0,
    "process": "1",
    "shared_by": null,
    "pre_size": "ten wide",
    "height": "300",
    "pre_height": "450",
    "enable_header_menu": "False",
    "enable_resize": "False"
}
"""

testcase_by_feature="""
{
    "id": 113,
    "title": "Test Case by Feature",
    "name": "testcase_by_feature",
    "type": "chart",
    "url": "/perfweb/pdashboard/dashboards/?board=testcase_by_feature&group=scheduler_testcase",
    "search": "select count(*) as y_data, feature as l_data from pperfscheduler_perftest where pperfscheduler_perftest.group=\"${group}\" and branch=\"${branch}\" group by feature;",
    "search_param": "{\"limit\":\"1\", \"offset\":\"0\", \"height\":\"200\", \"title_text\":\"By Feature\",\"y_name\": \"Number\", \"group\": \"perf\", \"branch\": \"develop\"}",
    "fixed_data": "0",
    "color": "green",
    "size": "eight wide",
    "state": "show",
    "created_at": "2017-12-15T23:08:54.639724",
    "updated_at": "2017-12-16T16:02:07.112228",
    "created_by": "default",
    "group": "scheduler_testcase",
    "comment": "Application scheduler owns the board",
    "index": 10,
    "template": "echart_board.html",
    "js_template": "basic_pie_echart_board.js",
    "status": "enable",
    "refresh": 0,
    "process": "1",
    "shared_by": null,
    "pre_size": "ten wide",
    "height": "300",
    "pre_height": "450",
    "enable_header_menu": "False",
    "enable_resize": "False"
}
"""

latest_job_status_policy="""
{
    "id": 121,
    "title": "Latest Job Status by Policy",
    "name": "latest_job_status_by_policy",
    "type": "chart",
    "url": "/perfweb/pdashboard/dashboards/?board=latest_job_status_by_policy&group=scheduler_job",
    "search": "select count(*) as y, s.ph_id as x, j.status as legend from pperfscheduler_perftestscheduler as j, (select s1.id, s1.policy_name, s1.ph_id from pperfscheduler_perfscheduler as s1 left join pperfscheduler_perfscheduler s2 on (s1.policy_name = s2.policy_name and s1.id < s2.id) where (s2.id is NULL or s1.ph_id like '${ph_id}%') and s1.policy_name in (select distinct(name) from pperfscheduler_perfpolicy where pperfscheduler_perfpolicy.trigger=\"cron\")) as s where j.scheduler_id = s.id group by s.ph_id, j.status limit ${limit} offset 0",
    "search_param": "{\"ph_id\": \"NOT_EXIST\", \"limit\":\"100000\", \"offset\":\"0\", \"height\":\"200\",\"yAxis\": {\"title\": {\"text\": \"Count\"}, \"minTickInterval\": 1},\"xAxis\": {\"title\": {\"text\": \"ph id\"}}, \"title\": {\"text\": \"Latest Job Status by Policy\"}, \"series\":{\"All\": {\"visible\": \"true\"}}}",
    "fixed_data": "0",
    "color": "green",
    "size": "sixteen wide",
    "state": "show",
    "created_at": "2017-12-26T11:41:42.338467",
    "updated_at": "2018-01-04T18:00:47.994110",
    "created_by": "default",
    "group": "scheduler_job",
    "comment": "Application scheduler owns the board",
    "index": 30,
    "template": "echart_board.html",
    "js_template": "basic_column_category_highchart_board.js",
    "status": "enable",
    "refresh": 60,
    "process": "1",
    "shared_by": null,
    "pre_size": "ten wide",
    "height": "300",
    "pre_height": "450",
    "enable_header_menu": "True",
    "enable_resize": "True",
    "enable_save": "False"
}
"""

perf_daily_run_job_status_by_time="""
{
    "id": 122,
    "title": "Perf Daily Run Job Status by Time",
    "name": "perf_daily_run_job_status_by_time",
    "type": "chart",
    "url": "/perfweb/pdashboard/dashboards/?board=perf_daily_run_job_status_by_time",
    "search": "select count(j.status) as y, j.status as legend, DATE_FORMAT(s.created_at, '%Y-%m-%d %H:%I:%S') as x from pperfscheduler_perfscheduler as s, pperfscheduler_perftestscheduler as j, pperfscheduler_perfpolicy as p where s.id = j.scheduler_id and s.policy_name = p.name and s.policy_name = \"Daily Run\" group by DATE_FORMAT(s.created_at, '%Y-%m-%d %H:%I:%S'), j.status",
    "search_param": "{\"limit\":\"100000\", \"offset\":\"0\", \"height\":\"200\", \"yAxis\": {\"title\": {\"text\": \"Test Case Number\"}, \"minTickInterval\": 1}, \"title\": {\"text\": \"Daily Run Job Status by Time\"}, \"series\":{\"All\": {\"visible\": \"true\"}}}",
    "fixed_data": "0",
    "color": "green",
    "size": "eight wide",
    "state": "show",
    "created_at": "2017-12-26T14:02:29.590738",
    "updated_at": "2017-12-26T14:03:50.691179",
    "created_by": "default",
    "group": "public",
    "comment": "Application scheduler owns the board",
    "index": 20,
    "template": "echart_board.html",
    "js_template": "basic_highchart_board.js",
    "status": "enable",
    "refresh": 0,
    "process": "1",
    "shared_by": null,
    "pre_size": "ten wide",
    "height": "350",
    "pre_height": "450",
    "enable_header_menu": "True",
    "enable_resize": "True"
}
"""

perf_daily_run_job_duration_by_time="""
{
    "id": 123,
    "title": "Perf Daily Run Job Duration by Time",
    "name": "perf_daily_run_job_duration_by_time",
    "type": "chart",
    "url": "/perfweb/pdashboard/dashboards/?board=perf_daily_run_job_duration_by_time",
    "search": "select TIMESTAMPDIFF(SECOND, created_at, ended_at) as y, DATE_FORMAT(created_at, '%Y-%m-%d %H:%I:%S') as x, policy_name as legend from pperfscheduler_perfscheduler where status = 'done' and policy_name in (select distinct(name) from pperfscheduler_perfpolicy) and policy_name = 'Daily Run' limit ${limit} offset 0",
    "search_param": "{\"limit\":\"100000\", \"offset\":\"0\", \"height\":\"200\", \"yAxis\": {\"title\": {\"text\": \"Job Duration(sec)\"}, \"minTickInterval\": 1}, \"title\": {\"text\": \"Daily Run Job Duration by Time\"}, \"series\":{\"All\": {\"visible\": \"true\"}}}",
    "fixed_data": "0",
    "color": "green",
    "size": "eight wide",
    "state": "show",
    "created_at": "2017-12-26T14:02:59.814736",
    "updated_at": "2017-12-26T14:04:07.155890",
    "created_by": "default",
    "group": "public",
    "comment": "Application scheduler owns the board",
    "index": 21,
    "template": "echart_board.html",
    "js_template": "basic_highchart_board.js",
    "status": "enable",
    "refresh": 0,
    "process": "1",
    "shared_by": null,
    "pre_size": "ten wide",
    "height": "350",
    "pre_height": "450",
    "enable_header_menu": "True",
    "enable_resize": "True"
}
"""

perf_weekly_regression_job_status_by_time="""
{
    "id": 128,
    "title": "Perf Weekly Regression Job Status by Time",
    "name": "perf_weekly_regression_job_status_by_time",
    "type": "chart",
    "url": "/perfweb/pdashboard/dashboards/?board=perf_weekly_regression_job_status_by_time",
    "search": "select count(j.status) as y, j.status as legend, DATE_FORMAT(s.created_at, '%Y-%m-%d %H:%I:%S') as x from pperfscheduler_perfscheduler as s, pperfscheduler_perftestscheduler as j, pperfscheduler_perfpolicy as p where s.id = j.scheduler_id and s.policy_name = p.name and s.policy_name = \"Weekly Regression\" group by DATE_FORMAT(s.created_at, '%Y-%m-%d %H:%I:%S'), j.status",
    "search_param": "{\"limit\":\"100000\", \"offset\":\"0\", \"height\":\"200\", \"yAxis\": {\"title\": {\"text\": \"Test Case Number\"}, \"minTickInterval\": 1}, \"title\": {\"text\": \"Weekly Regression Job Status by Time\"}, \"series\":{\"All\": {\"visible\": \"true\"}}}",
    "fixed_data": "0",
    "color": "green",
    "size": "eight wide",
    "state": "show",
    "created_at": "2017-12-26T14:08:07.990529",
    "updated_at": "2017-12-26T14:10:32.919688",
    "created_by": "default",
    "group": "public",
    "comment": "Application scheduler owns the board",
    "index": 22,
    "template": "echart_board.html",
    "js_template": "basic_highchart_board.js",
    "status": "enable",
    "refresh": 0,
    "process": "1",
    "shared_by": null,
    "pre_size": "ten wide",
    "height": "350",
    "pre_height": "450",
    "enable_header_menu": "True",
    "enable_resize": "True"
}
"""

perf_weekly_regression_job_duration_by_time="""
{
    "id": 129,
    "title": "Perf Weekly Regression Job Duration by Time",
    "name": "perf_weekly_regression_job_duration_by_time",
    "type": "chart",
    "url": "/perfweb/pdashboard/dashboards/?board=perf_weekly_regression_job_duration_by_time",
    "search": "select TIMESTAMPDIFF(SECOND, created_at, ended_at) as y, DATE_FORMAT(created_at, '%Y-%m-%d %H:%I:%S') as x, policy_name as legend from pperfscheduler_perfscheduler where status = 'done' and policy_name in (select distinct(name) from pperfscheduler_perfpolicy) and policy_name = 'Weekly Regression' limit ${limit} offset 0",
    "search_param": "{\"limit\":\"100000\", \"offset\":\"0\", \"height\":\"200\", \"yAxis\": {\"title\": {\"text\": \"Job Duration(sec)\"}, \"minTickInterval\": 1}, \"title\": {\"text\": \"Weekly Regression Job Duration by Time\"}, \"series\":{\"All\": {\"visible\": \"true\"}}}",
    "fixed_data": "0",
    "color": "green",
    "size": "eight wide",
    "state": "show",
    "created_at": "2017-12-26T14:09:04.546795",
    "updated_at": "2017-12-26T14:11:01.353702",
    "created_by": "default",
    "group": "public",
    "comment": "Application scheduler owns the board",
    "index": 23,
    "template": "echart_board.html",
    "js_template": "basic_highchart_board.js",
    "status": "enable",
    "refresh": 0,
    "process": "1",
    "shared_by": null,
    "pre_size": "ten wide",
    "height": "350",
    "pre_height": "450",
    "enable_header_menu": "True",
    "enable_resize": "True"
}
"""

perf_scheduler_job_table="""
{
    "id": 206,
    "title": "Perf Scheduler Running Policy",
    "name": "perf_scheduler_job_table",
    "type": "table",
    "url": "/perfweb/pdashboard/dashboards/?group=scheduler_job",
    "search": null,
    "search_param": "{\"title\":[[\"Scheduler ID\", \"id\"], [\"Policy Name\", \"policy_name\"], [\"UCP Host\", \"ucp_host\"], [\"Used Container\", \"used_container\"], [\"Created At\", \"created_at\"], [\"Run By\", \"created_by\"], [\"Status\", \"status\"]], \"query\": \"select a.id, a.policy_name, a.ucp_host, a.used_container, a.created_at, a.created_by, a.status, d.img from pperfscheduler_perfscheduler as a, (select img, user_id from pfile_userimage where id in (select max(id) from pfile_userimage group by user_id)) as d, puser_user as e where a.status in ('created', 'running') and a.created_at between now() - interval ${time_token} and now() and a.created_by = e.username AND e.id = d.user_id\"}",
    "fixed_data": "0",
    "color": "purple",
    "size": "sixteen wide",
    "state": "show",
    "created_at": "2018-01-24T17:24:05.623390",
    "updated_at": "2018-01-25T17:13:03.570297",
    "created_by": "default",
    "group": "scheduler_job",
    "comment": "Scheduler Job Table",
    "index": 200,
    "template": "basic_table_board.html",
    "js_template": "table_scheduler_job.js",
    "status": "enable",
    "refresh": 0,
    "process": "1",
    "shared_by": null,
    "pre_size": "sixteen wide",
    "height": "1000",
    "pre_height": "598",
    "footer_height": 0,
    "enable_header_menu": "True",
    "enable_resize": "True",
    "enable_save": "False"
}
"""
perf_scheduler_pr_trigger_policy_table = """
{
    "title": "PR Trigger <Performance Smoke Test> Status",
    "name": "perf_scheduler_pr_trigger_policy_table",
    "type": "table",
    "url": "/perfweb/pdashboard/dashboards/?group=scheduler_pr_trigger",
    "search": null,
    "search_param": "{\"namespace\": \"perf_scheduler_pr_trigger_policy_table\", \"columns\":[{\"title\": \"Scheduler ID\", \"data\": \"id\", \"sClass\": \"Scheduler ID custom\", \"column_filter\": {\"type\": \"text\", \"bRegex\": true, \"bSmart\": false}}, {\"title\": \"Policy Name\", \"data\": \"policy_name\", \"sClass\": \"Policy Name custom\", \"column_filter\": {\"type\": \"text\", \"bRegex\": true, \"bSmart\": false}}, {\"title\": \"UCP Host\", \"data\": \"ucp_host\", \"sClass\": \"UCP Host custom\", \"column_filter\": {\"type\": \"text\", \"bRegex\": true, \"bSmart\": false}}, {\"title\": \"Used Container\", \"data\": \"used_container\", \"sClass\": \"Used Container custom\", \"column_filter\": {\"type\": \"number-range\", \"bRegex\": true, \"bSmart\": false}}, {\"title\": \"Created At\", \"data\": \"created_at\", \"sClass\": \"Created At custom\", \"column_filter\": {\"type\": \"text\", \"bRegex\": true, \"bSmart\": false}}, {\"title\": \"Run By\", \"data\": \"created_by\", \"sClass\": \"Run By custom\", \"sWidth\": \"10%\", \"column_filter\": {\"type\": \"text\", \"bRegex\": true, \"bSmart\": false}},{\"title\": \"Progress\", \"data\": \"id\", \"sClass\": \"Progress custom\", \"sWidth\": \"20%\", \"column_filter\": {\"type\": \"hidden\", \"bRegex\": true, \"bSmart\": false}}, {\"title\": \"Status\", \"data\": \"status\", \"sClass\": \"Status custom\", \"column_filter\": {\"type\": \"text\", \"bRegex\": true, \"bSmart\": false}}, {\"title\": \"Action\", \"data\": \"id\", \"sClass\": \"Action custom\", \"column_filter\": {\"type\": \"hidden\", \"bRegex\": true, \"bSmart\": false}}, {\"title\": \"Link\", \"data\": \"id\", \"sClass\": \"Link custom\", \"column_filter\": {\"type\": \"hidden\", \"bRegex\": true, \"bSmart\": false}}], \"query\": \"select a.id, a.policy_name, a.ucp_host, a.used_container, a.created_at, a.created_by, a.status, a.ph_id, d.img from pperfscheduler_perfscheduler as a, pperfscheduler_perfpolicy as b,  (select img, user_id from pfile_userimage where id in (select max(id) from pfile_userimage group by user_id)) as d, puser_user as e where a.policy_name like 'PR-trigger%' and a.created_at between now() - interval ${time_token} and now() and a.created_by = e.username AND e.id = d.user_id AND a.policy_name = b.name\"}",
    "fixed_data": "0",
    "color": "brown",
    "size": "sixteen wide",
    "state": "show",
    "created_by": "default",
    "group": "scheduler_pr_trigger",
    "comment": "Scheduler PR Job Table",
    "index": 200,
    "template": "basic_table_board.html",
    "js_template": "table_jquery_datatable_base.js,table_scheduler_pr_trigger_policy.decorator.js",
    "status": "enable",
    "refresh": 0,
    "process": "1",
    "shared_by": null,
    "pre_size": "sixteen wide",
    "height": "1000",
    "pre_height": "598",
    "footer_height": 0,
    "enable_header_menu": "True",
    "enable_resize": "True",
    "enable_save": "False"
}
"""
